name: ThreatAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python Threat.py
      env:
        BASE_URL: ${{ env.BASE_URL }}
        OPENAI_KEY: ${{ env.OPENAI_KEY }}
        TOKEN: ${{ env.TOKEN }}
